[settings]
disable_backends = ["asdf"] # improves security
npm.package_manager = "bun"

[tools]

aube = "latest" # js package manager
bat = "latest"
bottom = "latest" # process/system monitor tui
bun = "latest" # js package manager and runtime
cowsay = "latest"
deno = "latest" # js runtime
eza = "latest" # list files and directories (ls modern alternative)
fd = "latest" # find entries in your filesystem (find modern alternative)
fzf = "latest" # fuzzy finder
go = "latest"
gradle = "latest"
java = "temurin"
jj = "latest" # jujutsu
jq = "latest" # JSON processor
just = "latest" # just a command runner
kotlin = "latest"
hurl = "latest" # run and test HTTP requests
lazygit = "latest" # git TUI
lua = "latest"
# luajit = "latest"
lua-language-server = "latest"
make = "latest"
node = "latest" # js runtime
npm = "latest" # js package manager
opencode = "latest"
prettier = "latest" # opinionanted code formatter
ripgrep = "latest" # search tool (grep modern alternative)
rust = "latest"
rust-analyzer = "latest"
sd = "latest" # find-and-replace CLI (sed modern alternative)
starship = "latest"
stylua = "latest"
television = "latest"
tree-sitter = "latest"
vale = "latest" # linter for prose (Markdown, AsciiDoc, reStructuredText, HTML, etc.)
uv = "latest" # Python package and project manager
watchexec = "latest"
# xcbeautify = "latest" # format swift and xcodebuild command output
xh = "latest" # HTTP client CLI (curl modern alternative)
yazi = "latest" # terminal file manager
yt-dlp = "latest" # YouTube downloader
zig = "latest"

# "aqua:YS-L/csvlens" = "latest" # CSV viewer TUI

"cargo:jj-starship" = "latest"
"cargo:lazyjj" = "latest"

"go:golang.org/x/tools/gopls" = "latest"
"go:golang.org/x/tools/cmd/goimports" = "latest"

"npm:@earendil-works/pi-coding-agent" = "latest"
"npm:typescript" = "latest"

"pipx:hf" = "latest" # Hugging Face CLI
"pipx:litecli" = "latest" # SQLite CLI

[env]

GOPATH = "{{ env.HOME }}/.go"
_.path = [
    "~/.go/bin"
]

