# ------- #
# Options #
# ------- #

# Tmux options
#
# Inspired by https://github.com/tmux-plugins/tmux-sensible, which defines
# sensible defaults.

# Enable extended keys for proper key handling
set -s extended-keys on
set -s extended-keys-format csi-u
set -as terminal-features '*alacritty*:extkeys'
# set -as terminal-features 'xterm-ghostty:extkeys'

# Set default terminal to ensure compatibility
set -g default-terminal "tmux-256color"

# Enable 24-bit color support
set -sa terminal-overrides ",xterm*:Tc"

# Set escape time to 0 to prevent vim mode switching delay
set -s escape-time 0

# Increase scrollback buffer size
set -g history-limit 50000

# Diplay tmux messages for 4 seconds
set -g display-time 4000

# Refresh 'status-left' and 'status-right' more often
set -g status-interval 10

# Set emacs key bindings (used in tmux command prompt, `prefix + :`)
set -g status-keys emacs

# Enable focus events for terminals that support them
set -g focus-events on

# Set clipboard integration
set -g set-clipboard external

# ------------ #
# Key bindings #
# ------------ #

# Set prefix to Ctrl-a instead of Ctrl-b
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Split window
unbind s
unbind v
bind s split-window -h 
bind S split-window -v 

# Select window
bind a last-window
bind -r C-p previous-window
bind -r C-n next-window
bind C-j select-window -t 0
bind C-k select-window -t 1
bind C-l select-window -t 2
bind C-u select-window -t 3
bind C-i select-window -t 4
bind C-o select-window -t 5

# Reload config
bind-key R run-shell " \
	tmux source-file ${HOME}/.tmux.conf > /dev/null;   \
	tmux display-message 'Tmux config reloaded from ${HOME}/.tmux.conf' \
"

# Mouse mode
# set -g mouse on

# ------- #
# Plugins #
# ------- #

# List of plugins
set -g @tpm_plugins '       \
    tmux-plugins/tpm        \
    catppuccin/tmux#v2.1.3  \
    sainnhe/tmux-fzf        \
'

# ------------------------ #
# Catppuccin plugin config
# ------------------------ #
set -g @catppuccin_flavor 'frappe'

set -g @catppuccin_user "off"

set -g @catppuccin_window_current_text " #W"
set -g @catppuccin_window_default_text " #W"
set -g @catppuccin_window_text " #W"

# set -g @catppuccin_window_status_style 'rounded'
set -g @catppuccin_window_tabs_enabled on # or off to disable window_tabs

# Move the session name to the right
set -g status-left ""
set -g status-right '#[fg=#{@thm_crust},bg=#{@thm_teal}] #S '

# ---------------------- #
# tmux-fzf plugin config
# ----------------------- #

bind "C-w" run-shell -b "${HOME}/.tmux/plugins/tmux-fzf/scripts/window.sh switch"

# ------------------------ #
# Init tmux plugin manager
# ------------------------ #
run '~/.tmux/plugins/tpm/tpm
