# Enable extended keys for proper key handling
set -s extended-keys on
set -s extended-keys-format csi-u
set -as terminal-features 'xterm-ghostty:extkeys'

# Set default terminal to ensure compatibility
set-option -g default-terminal "screen-256color"

# Set escape time to 0 to prevent vim mode switching delay
set -s escape-time 0

# Set clipboard integration
set -g set-clipboard external

# Set prefix to Ctrl-a instead of Ctrl-b
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Increase the history scrollback limit
set -g history-limit 10000

# -------------------------------------
# Key binding
# -------------------------------------

# Split window
unbind s
unbind v
bind s split-window -h 
bind v split-window -v 

# Select window
bind a last-window
bind -r C-n select-window -t :-
bind -r C-m select-window -t :+
bind C-j select-window -t 0
bind C-k select-window -t 1
bind C-l select-window -t 2
bind C-u select-window -t 3
bind C-i select-window -t 4
bind C-o select-window -t 5

# Mouse mode
# set -g mouse on

# Plugins
set -g @tpm_plugins '   \
    tmux-plugins/tpm    \
    sainnhe/tmux-fzf    \
'

bind-key "C-w" run-shell -b "${HOME}/.tmux/plugins/tmux-fzf/scripts/window.sh switch"

# Initialize tmux plugin manager (must be at the botton of tmux.conf)
run '~/.tmux/plugins/tpm/tpm
