# ------- #
# Options #
# ------- #

# Tmux options
#
# Inspired by https://github.com/tmux-plugins/tmux-sensible, which defines
# sensible defaults.

# Enable extended keys for proper key handling
set -s extended-keys on
set -s extended-keys-format csi-u
set -as terminal-features '*alacritty*:extkeys'
# set -as terminal-features 'xterm-ghostty:extkeys'

# Set default terminal and enable 24-bit color support
set -g default-terminal "tmux-256color"
set -sa terminal-overrides ",xterm*:Tc"

# Set escape time to 0 to prevent vim mode switching delay
set -s escape-time 0

# Increase scrollback buffer size
set -g history-limit 50000

# Diplay tmux messages for 4 seconds
set -g display-time 4000

# Refresh 'status-left' and 'status-right' more often
set -g status-interval 10

# Set emacs key bindings (used in tmux command prompt, `prefix + :`)
set -g status-keys emacs

# Enable focus events for terminals that support them
set -g focus-events on

# Set clipboard integration
set -g set-clipboard external

# ------------ #
# Key bindings #
# ------------ #

# Set prefix to Ctrl-a instead of Ctrl-b
unbind C-b
set -g prefix C-space
bind C-space send-prefix

# Split window
unbind s
unbind v
bind s split-window -h 
bind S split-window -v 

# Select window
bind space last-window
bind -r C-p previous-window
bind -r C-n next-window
bind C-j select-window -t 0
bind C-k select-window -t 1
bind C-l select-window -t 2
bind C-u select-window -t 3
bind C-i select-window -t 4
bind C-o select-window -t 5

# Reload config
bind-key R run-shell " \
	tmux source-file ${HOME}/.tmux.conf > /dev/null;   \
	tmux display-message 'Tmux config reloaded from ${HOME}/.tmux.conf' \
"

# Mouse mode
# set -g mouse on

# ---------- #
# Status bar #
# ---------- #

# Color palette (inspired by Tokyo night - night variant)
set -g @bar-bg '#16161e'
set -g @bar-fg '#a8B1d6'

set -g @blue-1-bg '#7aa2F7'
set -g @blue-1-fg '#15161e'
set -g @blue-2-bg '#3b4261'
set -g @blue-2-fg '#7aa2F7'

set -g @green-1-bg '#9ece6a'
set -g @green-1-fg '#15161e'
set -g @green-2-bg '#3b4261'
set -g @green-2-fg '#94c06a'

set -g @grey-1-bg '#939cbb'
set -g @grey-1-fg '#242634'
set -g @grey-2-bg '#3b4261'
set -g @grey-2-fg '#b8c0e0'

set -g @purple-1-bg '#bb9af7'
set -g @purple-1-fg '#15161e'
set -g @purple-2-bg '#3b4261'
set -g @purple-2-fg '#b697f1'

set -g @yellow-1-bg '#e0af69'
set -g @yellow-1-fg '#222023'
set -g @yellow-2-bg '#3b4261'
set -g @yellow-2-fg '#e0af69'

# Status bar style
set -g status-style bg="#{@bar-bg}",fg="#{@bar-fg}"

# Left: empty 
set -g status-left ""

# Window status
set -g window-status-format "#[bg=#{@grey-1-bg},fg=#{@grey-1-fg}] #I #[bg=#{@grey-2-bg},fg=#{@grey-2-fg}] #W "
set -g window-status-current-format "#[bg=#{@blue-1-bg},fg=#{@blue-1-fg},bold] #I #[bg=#{@grey-2-bg},fg=#{@grey-2-fg},bold] #W "
set -g window-status-separator "#[bg=#{@bar-bg}] "

# Right: session + hostname
set -g status-right "#[bg=#{@green-2-bg},fg=#{@green-2-fg}] #S #[bg=#{@bar-bg}] #[bg=#{@yellow-2-bg},fg=#{@yellow-2-fg}] @#h "

# ------- #
# Plugins #
# ------- #

# List of plugins
set -g @tpm_plugins '       \
    tmux-plugins/tpm        \
    sainnhe/tmux-fzf        \
'

# ---------------------- #
# tmux-fzf plugin config
# ----------------------- #

bind "C-w" run-shell -b "${HOME}/.tmux/plugins/tmux-fzf/scripts/window.sh switch"

# ------------------------ #
# Init tmux plugin manager
# ------------------------ #
run '~/.tmux/plugins/tpm/tpm
